{% set version = "4.3.2" %}
{% set build = 1 %}

# give conda package a higher build number
{% if mpi_type == 'conda' %}
{% set build = build + 100 %}
{% endif %}

package:
  # must not match any outputs for requirements to be handled correctly
  name: mpich-mpi
  version: {{ version }}

source:
  fn: mpich-{{ version }}.tar.gz
  url: https://www.mpich.org/static/downloads/{{ version }}/mpich-{{ version }}.tar.gz
  sha256: 47d774587a7156a53752218c811c852e70ac44db9c502dc3f399b4cb817e3818

build:
  number: {{ build }}
  skip: true  # [win]

outputs:
  - name: mpich
    {% if mpi_type == 'conda' %}
    script: build-mpi.sh
    {% endif %}
    build:
      {% if mpi_type == 'conda' %}
      run_exports:
        - {{ pin_subpackage('mpich', max_pin='x') }}
      {% else %}
      string: {{ mpi_type }}_h{{ PKG_HASH }}_{{ build }}
      track_features:
        # four total features is a hack for solver
        # priority issues in https://github.com/conda-forge/mpich-feedstock/issues/95
        # the rule is that the number of features here has to be greater than the sum
        # of the number of features across all possible dependencies of the non-external
        # packages. See https://github.com/conda-forge/mpich-feedstock/issues/95#issuecomment-3617935263
        # some manual queries of the repodata indicated that as of late 2025, this sum was ~2.
        # we are using four total here to have a buffer.
        # if this number ever changes, all previous external builds need to be patched to
        # match the same number. Otherwise, chaos. - MRB (beckermr)
        - mpich_{{ mpi_type }}
        - mpich_{{ mpi_type }}_1
        - mpich_{{ mpi_type }}_2
        - mpich_{{ mpi_type }}_3
      {% endif %}
    requirements:
      {% if mpi_type == 'conda' %}
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler('fortran') }}
        - {{ stdlib("c") }}
        - make
        # FIXME: autoconf/automake/libtool required to apply PR 6932 patch
        - autoconf
        - automake
        - libtool
        - gnuconfig  # [osx and arm64]
      host:
        - libfabric-devel {{ libfabric }}.*
        - libhwloc
        - ucx  # [linux and not ppc64le]
      {% endif %}
      run:
        - mpi 1.0.* mpich
    test:
      {% if mpi_type == 'conda' %}
      script: run_test.sh
      files:
        - mpiexec.sh
        - tests/helloworld.sh
      {% endif %}
      commands:
      {% if mpi_type == 'conda' %}
        - test ! -f $PREFIX/doc/mpich
        - test ! -f $PREFIX/share/man/man3/MPI_Barrier.3
      {% else %}
        - echo "It works!"
      {% endif %}

  {% if mpi_type == 'conda' %}
  - name: mpich-mpicc
    build:
      script:
        - echo 'ok'
    requirements:
      run:
        - {{ pin_subpackage('mpich', exact=True) }}
        # host C compilers work fine (better) on mac
        - {{ compiler('c') }}
    test:
      script: run_test.sh
      files:
        - mpiexec.sh
        - tests/helloworld.c

  - name: mpich-mpicxx
    build:
      script:
        - echo 'ok'
    requirements:
      run:
        - {{ pin_subpackage('mpich', exact=True) }}
        # host C compilers work fine (better) on mac
        - {{ compiler('cxx') }}
    test:
      script: run_test.sh
      files:
        - mpiexec.sh
        - tests/helloworld.cxx

  - name: mpich-mpifort
    build:
      script:
        - echo 'ok'
    requirements:
      run:
        - {{ pin_subpackage('mpich', exact=True) }}
        - {{ compiler('fortran') }}
    test:
      script: run_test.sh
      files:
        - mpiexec.sh
        - tests/helloworld.f
        - tests/helloworld.f90
        - tests/helloworld.f08
  {% endif %}

about:
  home: https://www.mpich.org/
  license: LicenseRef-MPICH
  license_file: COPYRIGHT
  license_family: Other
  summary: A high performance widely portable implementation of the MPI standard.
  description: |
    MPICH is a high performance and widely portable implementation of the
    Message Passing Interface (MPI) standard.
  doc_url: https://www.mpich.org/documentation/guides
  dev_url: https://github.com/pmodels/mpich

extra:
  recipe-maintainers:
    - astrofrog
    - bekozi
    - dalcinl
    - minrk
    - msarahan
    - ocefpaf
    - j34ni
