appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: vJJpz8X04+qkbwBMm2Vzq+jZVRYLSll6l7BvE7BsjISLWXzqcHX4v0WghSi4JKs7ejDKABrd1GPBt2gGL9/nODQh7O2BxWt6lDzyJHg+gy/kufSNqmOpGOYKJw5twlh8ogynz2ZH/CYJe9+k961WAP6k6yHQtw5MWizF7M5e/dxdMPolFXQivz7i+Yj5gGZ0LfC/hNdwYX4jO/I9O1vLQX5K2vvl0uxbh3vLD9e4i3mL9K1kPmcJ8HMvLM8lKvjc/ZE0/3zCUtAuRGAvtEDJimpH0Iih3WFazXod8dZJw71gmxaiynHfv0dZDkIMDqs0VpLKbBdgcfyXlFT4nE6homAKL1XnvNCIbd9dEOYx7Rx72YmPy06tBHBYNEAjvY93lFIvSR2JhPoKRsfh+sfBXmDOBTHkYWrkBM07rvi7nXqx0aO+MLT40NLlJW83QNQ6Vwp1kZG73egwZcXPjbsL0K+AMVoWA/tFxVbWY87KYGui1sn4JropaPAiQSRUvUUt32HTMfUCgFAIVPMYR+JpOB5QaHttejGYlYCmOjrAGF9QEB0NltjX8L0y3O5/Q/dKjFv4V8LUODyLeLAFA/yoqa/KtGniriY7lOyiXPOPD52y+zaDugzSqc4rMLPYy/UVEpAdPEfK2H/x90mi6wRgUvmKEpLmgFEzIR/1pr+rPQY=}
